"""add one-to-one and family registration tables

Revision ID: 2ad195a12582
Revises: 006
Create Date: 2026-06-05 12:10:27.774041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad195a12582'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matches_id', table_name='matches')
    op.drop_index('ix_matches_stage', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_player_registrations_id', table_name='player_registrations')
    op.drop_table('player_registrations')
    op.drop_index('ix_admin_users_id', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('ix_BNI_registration_family_registrations_id', table_name='family_registrations')
    op.drop_table('family_registrations')
    op.drop_index('ix_BNI_registration_one_to_one_registrations_id', table_name='one_to_one_registrations')
    op.drop_table('one_to_one_registrations')
    op.drop_table('alembic_version')
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_news_posts_category', table_name='news_posts')
    op.drop_index('ix_news_posts_id', table_name='news_posts')
    op.drop_index('ix_news_posts_published', table_name='news_posts')
    op.drop_table('news_posts')
    op.drop_index('ix_admin_users_id', table_name='admin_users', schema='BNI_registration')
    op.create_index(op.f('ix_BNI_registration_admin_users_id'), 'admin_users', ['id'], unique=False, schema='BNI_registration')
    op.drop_index('ix_matches_id', table_name='matches', schema='BNI_registration')
    op.drop_index('ix_matches_stage', table_name='matches', schema='BNI_registration')
    op.create_index(op.f('ix_BNI_registration_matches_id'), 'matches', ['id'], unique=False, schema='BNI_registration')
    op.drop_index('ix_news_posts_category', table_name='news_posts', schema='BNI_registration')
    op.drop_index('ix_news_posts_id', table_name='news_posts', schema='BNI_registration')
    op.drop_index('ix_news_posts_published', table_name='news_posts', schema='BNI_registration')
    op.create_index(op.f('ix_BNI_registration_news_posts_id'), 'news_posts', ['id'], unique=False, schema='BNI_registration')
    op.alter_column('player_registrations', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               schema='BNI_registration')
    op.drop_index('ix_player_registrations_id', table_name='player_registrations', schema='BNI_registration')
    op.create_index(op.f('ix_BNI_registration_player_registrations_id'), 'player_registrations', ['id'], unique=False, schema='BNI_registration')
    op.drop_index('ix_teams_id', table_name='teams', schema='BNI_registration')
    op.create_index(op.f('ix_BNI_registration_teams_id'), 'teams', ['id'], unique=False, schema='BNI_registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BNI_registration_teams_id'), table_name='teams', schema='BNI_registration')
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False, schema='BNI_registration')
    op.drop_index(op.f('ix_BNI_registration_player_registrations_id'), table_name='player_registrations', schema='BNI_registration')
    op.create_index('ix_player_registrations_id', 'player_registrations', ['id'], unique=False, schema='BNI_registration')
    op.alter_column('player_registrations', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               schema='BNI_registration')
    op.drop_index(op.f('ix_BNI_registration_news_posts_id'), table_name='news_posts', schema='BNI_registration')
    op.create_index('ix_news_posts_published', 'news_posts', ['is_published'], unique=False, schema='BNI_registration')
    op.create_index('ix_news_posts_id', 'news_posts', ['id'], unique=False, schema='BNI_registration')
    op.create_index('ix_news_posts_category', 'news_posts', ['category'], unique=False, schema='BNI_registration')
    op.drop_index(op.f('ix_BNI_registration_matches_id'), table_name='matches', schema='BNI_registration')
    op.create_index('ix_matches_stage', 'matches', ['stage'], unique=False, schema='BNI_registration')
    op.create_index('ix_matches_id', 'matches', ['id'], unique=False, schema='BNI_registration')
    op.drop_index(op.f('ix_BNI_registration_admin_users_id'), table_name='admin_users', schema='BNI_registration')
    op.create_index('ix_admin_users_id', 'admin_users', ['id'], unique=False, schema='BNI_registration')
    op.create_table('news_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'news'::character varying"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=150), server_default=sa.text("'BNI-TPL Admin'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_posts_pkey'),
    sa.UniqueConstraint('slug', name='news_posts_slug_key')
    )
    op.create_index('ix_news_posts_published', 'news_posts', ['is_published'], unique=False)
    op.create_index('ix_news_posts_id', 'news_posts', ['id'], unique=False)
    op.create_index('ix_news_posts_category', 'news_posts', ['category'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    sa.UniqueConstraint('name', name='teams_name_key')
    )
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('one_to_one_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('business_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='one_to_one_registrations_pkey')
    )
    op.create_index('ix_BNI_registration_one_to_one_registrations_id', 'one_to_one_registrations', ['id'], unique=False)
    op.create_table('family_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('age_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('business_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='family_registrations_pkey')
    )
    op.create_index('ix_BNI_registration_family_registrations_id', 'family_registrations', ['id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey'),
    sa.UniqueConstraint('username', name='admin_users_username_key')
    )
    op.create_index('ix_admin_users_id', 'admin_users', ['id'], unique=False)
    op.create_table('player_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('jersey_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('jersey_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jersey_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('lower_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='player_registrations_pkey')
    )
    op.create_index('ix_player_registrations_id', 'player_registrations', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team1_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('team2_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('team1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team2_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team1_overs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('team2_overs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_overs', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'20'::double precision"), autoincrement=False, nullable=False),
    sa.Column('winner', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('match_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=20), server_default=sa.text("'league'::character varying"), autoincrement=False, nullable=False),
    sa.Column('match_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='matches_pkey')
    )
    op.create_index('ix_matches_stage', 'matches', ['stage'], unique=False)
    op.create_index('ix_matches_id', 'matches', ['id'], unique=False)
    # ### end Alembic commands ###
